name: build

on:
  push:
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Dafny
        uses: dafny-lang/setup-dafny-action@v1
        with:
          dafny-version: "3.7.3"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run Gradle Build
        run: gradle build
