name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Dafny
        uses: dafny-lang/setup-dafny-action@v1
        with:
          dafny-version: "3.8.1"

      - name: Z3 version
        run: $HOME/dafny/z3/bin/z3 --version

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run Gradle Build
        run: gradle build
