name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Dafny
        uses: dafny-lang/setup-dafny-action@v1.7.0
        with:
          dafny-version: "4.4.0"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.4.2

      - name: Set DAFNY_HOME
        run: echo "DAFNY_HOME=$(dirname $(which dafny))" >> $GITHUB_ENV
    
  build-java:
    needs: setup
    steps:
      - name: Gradle Build
        run: gradle build -Prandomize=5
      
      - name: Verification Logs (EVM)
        if: always()
        run: gradle debug --args="build/logs/verify.csv"

      - name: Verification Logs (Proofs)
        if: always()
        run: gradle debug --args="build/logs/test_*.csv"

  build-go:
    needs: setup
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Makefile Build
        run: make

  test-z3-4-8-5:
    needs: setup    
    steps:
      - name: Gradle Test
        run: gradle test -Prandomize=5 -Psolver-path=$DAFNY_HOME/z3/bin/z3-4.8.5

      - name: Verification Logs (EVM)
        if: always()
        run: gradle debug --args="build/logs/verify.csv"

      - name: Verification Logs (Proofs)
        if: always()
        run: gradle debug --args="build/logs/test_*.csv"
