name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Dafny
        uses: dafny-lang/setup-dafny-action@v1.6.1
        with:
          dafny-version: "4.2.0"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.4.2

      - name: Find Z3
        run: which dafny

      - name: Find Z3(2)
        run: echo $(which dafny | sed -e "s/dafny/z3\/bin\/z3-4.8.5/")

      - name: Run Gradle Build
        run: gradle build -Prandomize=5

      - name: Verification Logs (EVM)
        if: always()
        run: gradle debug --args="build/logs/verify.csv"

      - name: Verification Logs (Proofs)
        if: always()
        run: gradle debug --args="build/logs/test_*.csv"

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build with the Makefile
        run: make
