name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build-java:
    runs-on: ubuntu-latest    
    steps:
        # Setup
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: adopt
          cache: 'gradle'        
      - uses: dafny-lang/setup-dafny-action@v1.7.0
        with:
          dafny-version: "4.4.0"
      - name: Set DAFNY_HOME
        run: echo "DAFNY_HOME=$(dirname $(which dafny))" >> $GITHUB_ENV
        # Build
      - name: Gradle Build
        run: gradle --no-daemon build -Prandomize=5
        # Report
      - name: Verification Logs (EVM)
        if: always()
        run: gradle --no-daemon debug --args="build/logs/verify.csv"
      - name: Verification Logs (Proofs)
        if: always()
        run: gradle --no-daemon debug --args="build/logs/test_*.csv"

  test-z3-4-8-5:
    runs-on: ubuntu-latest    
    steps:
        # Setup
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: adopt
          cache: 'gradle'    
      - uses: dafny-lang/setup-dafny-action@v1.7.0
        with:
          dafny-version: "4.4.0"
      - name: Set DAFNY_HOME
        run: echo "DAFNY_HOME=$(dirname $(which dafny))" >> $GITHUB_ENV
        # Build
      - name: Gradle Test
        run: gradle --no-daemon test -Prandomize=5 -Psolver-path=$DAFNY_HOME/z3/bin/z3-4.8.5
        # Report
      - name: Verification Logs (EVM)
        if: always()
        run: gradle --no-daemon debug --args="build/logs/verify.csv"
      - name: Verification Logs (Proofs)
        if: always()
        run: gradle --no-daemon debug --args="build/logs/test_*.csv"
